# Generated by Django 5.2.17 on 2026-09-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('quantity', models.IntegerField()),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('EXPIRED', 'Expired'), ('UNUSABLE', 'Unusable')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Blood Batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('available_units', models.IntegerField(default=0)),
                ('reserved_units', models.IntegerField(default=0)),
                ('in_transit_units', models.IntegerField(default=0)),
                ('expired_units', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Blood Inventories',
                'ordering': ['facility', 'blood_group'],
                'unique_together': {('facility', 'blood_group')},
            },
        ),
    ]
