# Generated by Django 5.2.17 on 2026-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodinventory',
            options={'ordering': ['facility', 'blood_group', 'blood_component'], 'verbose_name_plural': 'Blood Inventories'},
        ),
        migrations.AlterUniqueTogether(
            name='bloodinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bloodbatch',
            name='blood_component',
            field=models.CharField(choices=[('RBC', 'Red Blood Cells (PRBC)'), ('WBC', 'White Blood Cells (Granulocytes)'), ('Plasma', 'Fresh Frozen Plasma (FFP)'), ('Platelets', 'Platelets (Platelet Concentrate)'), ('Cryoprecipitate', 'Cryoprecipitate'), ('Whole Blood', 'Whole Blood')], default='RBC', max_length=30),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='blood_component',
            field=models.CharField(choices=[('RBC', 'Red Blood Cells (PRBC)'), ('WBC', 'White Blood Cells (Granulocytes)'), ('Plasma', 'Fresh Frozen Plasma (FFP)'), ('Platelets', 'Platelets (Platelet Concentrate)'), ('Cryoprecipitate', 'Cryoprecipitate'), ('Whole Blood', 'Whole Blood')], default='RBC', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='bloodinventory',
            unique_together={('facility', 'blood_group', 'blood_component')},
        ),
        migrations.CreateModel(
            name='FacilityDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(db_index=True, max_length=20)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=50)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('blood_group', models.CharField(db_index=True, max_length=10)),
                ('blood_component', models.CharField(db_index=True, max_length=50)),
                ('units_requested', models.IntegerField(default=0)),
                ('units_issued', models.IntegerField(default=0)),
                ('units_received', models.IntegerField(default=0)),
                ('units_transferred_out', models.IntegerField(default=0)),
                ('units_expired', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Facility Daily Record',
                'verbose_name_plural': 'Facility Daily Records',
                'db_table': 'facility_daily_records',
                'indexes': [models.Index(fields=['facility_id', 'date'], name='facility_da_facilit_cc6de7_idx'), models.Index(fields=['district', 'date'], name='facility_da_distric_754897_idx'), models.Index(fields=['blood_group', 'blood_component'], name='facility_da_blood_g_e76fb8_idx')],
            },
        ),
    ]
