# Generated by Django 5.2.17 on 2026-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_component',
            field=models.CharField(choices=[('RBC', 'Red Blood Cells (PRBC)'), ('WBC', 'White Blood Cells (Granulocytes)'), ('Plasma', 'Fresh Frozen Plasma (FFP)'), ('Platelets', 'Platelets (Platelet Concentrate)'), ('Cryoprecipitate', 'Cryoprecipitate'), ('Whole Blood', 'Whole Blood')], default='RBC', max_length=30),
        ),
    ]
