# Generated by Django 5.2.17 on 2026-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_bloodrequest_blood_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency'), ('CRITICAL', 'Critical / STAT')], default='MEDIUM', max_length=20),
        ),
    ]
