# Generated by Django 5.2.17 on 2026-09-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('HOSPITAL', 'Hospital Admin / Full Workspace'), ('HOSPITAL_APPROVAL', 'Hospital Approval Desk'), ('HOSPITAL_LOGISTICS', 'Hospital Logistics'), ('BLOOD_BANK', 'Blood Bank')], max_length=30),
        ),
    ]
