# Generated by Django 6.1.1 on 2026-09-28 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('camp_name', models.CharField(max_length=300)),
                ('camp_type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('ROUTINE', 'Routine'), ('SPECIAL', 'Special Drive')], default='ROUTINE', max_length=20)),
                ('urgency', models.CharField(choices=[('CRITICAL', 'Critical'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('venue_name', models.CharField(max_length=300)),
                ('venue_address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('required_blood_groups', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('max_donors', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_camps', to='facilities.facility')),
            ],
            options={
                'db_table': 'donation_camps',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='REGISTERED', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_registrations', to='donors.donorprofile')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='camps.donationcamp')),
            ],
            options={
                'db_table': 'camp_registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units_donated', models.FloatField(default=1.0)),
                ('donation_datetime', models.DateTimeField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='camps.donationcamp')),
                ('camp_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camps.campregistration')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_donations', to='donors.donorprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_donations', to='facilities.facility')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verified_donations',
                'ordering': ['-donation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DonorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('CAMP_REGISTERED', 'Camp Registration'), ('CAMP_REMINDER', 'Camp Reminder'), ('CAMP_CANCELLED', 'Camp Cancelled'), ('CAMP_UPDATED', 'Camp Updated'), ('DONATION_VERIFIED', 'Donation Verified'), ('CERTIFICATE_READY', 'Certificate Ready'), ('ACHIEVEMENT_UNLOCKED', 'Achievement Unlocked'), ('EMERGENCY_CAMP', 'Emergency Camp'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='donors.donorprofile')),
                ('related_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camps.donationcamp')),
                ('related_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camps.verifieddonation')),
            ],
            options={
                'db_table': 'donor_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('facility_name', models.CharField(max_length=300)),
                ('camp_name', models.CharField(max_length=300)),
                ('donation_date', models.DateField()),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='donors.donorprofile')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='camps.verifieddonation')),
            ],
            options={
                'db_table': 'donation_certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donationcamp',
            index=models.Index(fields=['status', 'start_datetime'], name='donation_ca_status_eb68e2_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcamp',
            index=models.Index(fields=['organizer', 'status'], name='donation_ca_organiz_611d25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campregistration',
            unique_together={('camp', 'donor')},
        ),
    ]
