# Generated by Django 6.1.1 on 2026-09-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campregistration',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='preferred_timeslot',
            field=models.CharField(blank=True, default='09:00 AM - 10:00 AM', max_length=100),
        ),
    ]
