# Generated by Django 6.1.1 on 2026-09-28 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_campregistration_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campregistration',
            name='qr_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
