# Generated by Django 5.2.17 on 2026-09-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('APPROVAL_PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('DISPATCHED', 'Dispatched'), ('OTP_PENDING', 'OTP Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='CREATED', max_length=30)),
                ('otp_code_hash', models.CharField(blank=True, default='', max_length=128)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='facilities.facility')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='requests.bloodrequest')),
                ('request_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.requestallocation')),
                ('sender_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='facilities.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
