# Generated by Django 5.2.17 on 2026-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtransfer',
            name='latest_otp_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
