# Generated by Django 5.2.17 on 2026-09-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(db_index=True, max_length=100, unique=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('training_data_start', models.DateField()),
                ('training_data_end', models.DateField()),
                ('validation_data_start', models.DateField(blank=True, null=True)),
                ('validation_data_end', models.DateField(blank=True, null=True)),
                ('total_series_trained', models.IntegerField(default=0)),
                ('total_predictions_generated', models.IntegerField(default=0)),
                ('xgb_mae', models.FloatField(blank=True, null=True)),
                ('xgb_rmse', models.FloatField(blank=True, null=True)),
                ('xgb_wape', models.FloatField(blank=True, null=True)),
                ('baseline_mae', models.FloatField(blank=True, null=True)),
                ('baseline_rmse', models.FloatField(blank=True, null=True)),
                ('baseline_wape', models.FloatField(blank=True, null=True)),
                ('facilities_with_sufficient_data', models.IntegerField(default=0)),
                ('facilities_insufficient_data', models.IntegerField(default=0)),
                ('data_quality_warnings', models.TextField(default='[]')),
                ('config_json', models.TextField(default='{}')),
            ],
            options={
                'db_table': 'model_metadata',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(db_index=True, max_length=50)),
                ('facility_type', models.CharField(default='Hospital', max_length=50)),
                ('forecast_target', models.CharField(default='units_requested', max_length=50)),
                ('blood_group', models.CharField(db_index=True, max_length=10)),
                ('blood_component', models.CharField(db_index=True, max_length=50)),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted_units', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(db_index=True, max_length=100)),
                ('actual_units', models.FloatField(blank=True, null=True)),
                ('prediction_error', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demand_predictions',
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['facility_id', 'blood_group', 'blood_component', 'forecast_date'], name='demand_pred_facilit_512a94_idx'), models.Index(fields=['facility_id', 'model_version'], name='demand_pred_facilit_212c0e_idx')],
            },
        ),
    ]
